### ISSUE TITLE
Error: Unable to place item

### ISSUE THREAD

**Issue by chasenlehara** [canjs/can-view-live#150]
[Filing this issue here because can-view-live is what throws the error, but this repo might not be where the issue is.]

With can@6.2.2 (and can-view-live@5.0.0), this error is hit with the below CodePen: https://github.com/canjs/can-view-live/blob/0f1600fbbdedd3a84181a8e236ba88b3101fdc92/lib/list.js#L209

When using CodePen: https://codepen.io/bitovi/pen/MWWERjV

Steps to reproduce:

1. Load the CodePen
2. Click the Hide button
3. Click the Show button

Expected results: no error is thrown.

Actual results: an “Unable to place item” error is thrown.

This error happens in the DoneJS chat example that I’m upgrading from CanJS 5. I’ve tried to pare the example down. The `#for` loop is required, as is having multiple `bit-panel` elements in the DOM, and hiding/showing them.

**Comment by bmomberger-bitovi** [comment]
Copied from a slack message:

> The root of this bug is, if you have the ListDOMPatcher batch two adds, it sends both tasks to the DomOrderQueue using the same function (this.add).  DOMOrderQueue only accepts one task per function at a time, though; if the same function is queued twice, its task is updated with the new context and args.
