### ISSUE TITLE
"Error: Unable to place item" on empty list - Broken on Can@6

### ISSUE THREAD

**Issue by h8h** [canjs/can-view-live#159]
Hi,

-- edit --
It seems that upgrading from can@5 to can@6 leads to the behavior described below.
It evens breaks your Basic Todo App.

Reproducing:
1. Open the codepen page https://codepen.io/bitovi/pen/dBKzBZ
2. On the right pane (JS) change line 5
```
import { realtimeRestModel, StacheElement, type } from "//unpkg.com/can@5/everything.mjs";
```
to
```
import { realtimeRestModel, StacheElement, type } from "//unpkg.com/can@6/everything.mjs";
```
<small>notice the digit 5 ->  6</small>

3. Remove every item on the list
4. Add a new item to the list

Result: No new item is added to the list.

--- / edit ----

I'm new to canjs and I would like to use it with [FastAPI](https://github.com/tiangolo/fastapi).

I actually copied your [TODO](https://codepen.io/bitovi/pen/dBKzBZ) demonstration and replaced the backend api with FastAPI.

Reproducing:
1. Remove every todo items from the todo list
2. Add a new todo to the todo list. For example my api returns:
```
{"id":"b86f8aad-d04f-4fe1-9fb5-2b6902704862","name":"test3","complete":false}
```

Expected behavior:
The new items get added to the list

Current behavior:
An error is thrown, the new item does not get added to the list.
```
Uncaught (in promise) Error: Unable to place item
    at ListDOMPatcher.add (list.js:231)
    at ListDOMPatcher.<anonymous> (list.js:181)
    at Array.forEach (<anonymous>)
    at ListDOMPatcher.processDomQueue (list.js:178)
    at DomOrderQueue.flush (dom-order-queue.js:114)
    at Object.onComplete (can-queues.js:50)
    at PriorityQueue.flush (priority-queue.js:122)
    at Object.onComplete (can-queues.js:35)
    at Queue.flush (queue.js:58)
    at Object.stop (can-queues.js:118)
```

It seems that the bug only exists in my project using your codepen example everything works. What do I wrong?

![Image of Bug](https://i.imgur.com/i8LuuCV.gif)

For the case this is the project: https://github.com/h8h/canjs_fastapi-TODO-example/.

I don't know if the bug is similar to this one #150 

Thanks!

**Comment by justinbmeyer** [comment]
Thanks!  I'll take a look at it this week.

**Comment by justinbmeyer** [comment]
This codepen is updated to point at CanJS 6: https://codepen.io/justinbmeyer/pen/jOBMgNd?editors=0010

**Comment by justinbmeyer** [comment]
Actually, this seems to be a problem with can-connect .... it's splicing an item in a list with an `undefined` position (like `.splice(undefined, 0, item)`)

**Comment by justinbmeyer** [comment]
fixed here: https://github.com/canjs/can-connect/pull/513
